apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  type: LoadBalancer
  selector:
    postgres-operator.crunchydata.com/pgadmin: rhino
  ports:
    - name: pgadmin
      port: 80
      targetPort: 5050
      protocol: TCP
